server:
  port: 8000
# 这是使用druid连接池的配置，其他的连接池配置可能有所不同
spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.209.131:3306/test_canal?serverTimezone=GMT%2B8
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.209.100:3306/test_canal?serverTimezone=GMT%2B8
        username: root
        password: root
      #slave1:
      #  type: com.alibaba.druid.pool.DruidDataSource
      #  driver-class-name: com.mysql.jdbc.Driver
      #  url: jdbc:mysql://192.168.0.110:3306/test_db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
      #  username: yehongzhi
      #  password: YHZ@1234
    props:
      sql.show: true
    masterslave:
      load-balance-algorithm-type: round_robin
    sharding:
      master-slave-rules:
        master:
          master-data-source-name: master
          slave-data-source-names: slave
          #slave-data-source-names: slave0,slave1
mybatis-plus:
  mapper-locations: classpath:com/yang/bootdemo/mapper/xml/*.xml
