datasource:
  serverName:
    list: config
  config:
    dataSourceInfoMap:
      "[cpprd]":
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://106.15.236.44:3306/db1?serverTimezone=GMT%2B8
        maximumPoolSize: 20
        minimumIdle: 2
        password: root
        username: root
      "[config]":
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://106.15.236.44:3306/db2?serverTimezone=GMT%2B8
        maximumPoolSize: 5
        password: root
        username: root
